version: "3.8"

services:
    db:
        container_name: main_db
        env_file:
            - .env.dev

        networks:
            - my-network
    
    pgadmin:
        container_name: pgadmin_v1
        env_file:
            - .env.dev
        
        networks:
            - my-network
        
        depends_on:
            - db

networks:
  my-network:



